services:

  postgres:
    container_name: nc-postgres
    build:
      context: .
      dockerfile: Postgres.dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATABASE: postgres
      PGUSER: postgres
      PGPORT: 5432
    volumes:
      - ./data/pg_dump/Ft:/data/pg_dump/Ft

  app:
    container_name: nc-python
    build:
      context: .
      dockerfile: Webserver.dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - ./data:/data
      - ./logs:/app/logs
      - ./netflix_critic_data/scripts/database_setup/common.py:/app/common.py
    environment:
      BRD_AUTH_TOKEN: ${BRD_AUTH_TOKEN}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password